//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSMS.Presentation.Impl.KitchenService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KitchenService.IKitchenService")]
    public interface IKitchenService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKitchenService/StopSupplyItem", ReplyAction="http://tempuri.org/IKitchenService/StopSupplyItemResponse")]
        void StopSupplyItem(System.Collections.Generic.List<HCSMS.Model.Item> itemList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKitchenServiceChannel : HCSMS.Presentation.Impl.KitchenService.IKitchenService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KitchenServiceClient : System.ServiceModel.ClientBase<HCSMS.Presentation.Impl.KitchenService.IKitchenService>, HCSMS.Presentation.Impl.KitchenService.IKitchenService {
        
        public KitchenServiceClient() {
        }
        
        public KitchenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KitchenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KitchenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KitchenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void StopSupplyItem(System.Collections.Generic.List<HCSMS.Model.Item> itemList) {
            base.Channel.StopSupplyItem(itemList);
        }
    }
}
