//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSMS.Presentation.Impl.FrontDeskRequest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FrontDeskRequest.IFrontDeskRequest", CallbackContract=typeof(HCSMS.Presentation.Impl.FrontDeskRequest.IFrontDeskRequestCallback))]
    public interface IFrontDeskRequest {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFrontDeskRequest/ListenToServer", ReplyAction="http://tempuri.org/IFrontDeskRequest/ListenToServerResponse")]
        void ListenToServer();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFrontDeskRequestCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFrontDeskRequest/ServeItem", ReplyAction="http://tempuri.org/IFrontDeskRequest/ServeItemResponse")]
        void ServeItem(System.Collections.Generic.List<HCSMS.Model.RequestHandleInfo> itemList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFrontDeskRequest/RequestDeny", ReplyAction="http://tempuri.org/IFrontDeskRequest/RequestDenyResponse")]
        void RequestDeny(System.Collections.Generic.List<HCSMS.Model.RequestHandleInfo> itemList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFrontDeskRequest/StopSupplyItem", ReplyAction="http://tempuri.org/IFrontDeskRequest/StopSupplyItemResponse")]
        void StopSupplyItem(string itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFrontDeskRequest/RunOutOfItem", ReplyAction="http://tempuri.org/IFrontDeskRequest/RunOutOfItemResponse")]
        void RunOutOfItem(string itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFrontDeskRequest/ErrorMessage", ReplyAction="http://tempuri.org/IFrontDeskRequest/ErrorMessageResponse")]
        void ErrorMessage(HCSMS.Model.Application.ErrorEventArgs error);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFrontDeskRequest/InformationMessage", ReplyAction="http://tempuri.org/IFrontDeskRequest/InformationMessageResponse")]
        void InformationMessage(HCSMS.Model.Application.NotifyEventArgs msg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFrontDeskRequestChannel : HCSMS.Presentation.Impl.FrontDeskRequest.IFrontDeskRequest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FrontDeskRequestClient : System.ServiceModel.DuplexClientBase<HCSMS.Presentation.Impl.FrontDeskRequest.IFrontDeskRequest>, HCSMS.Presentation.Impl.FrontDeskRequest.IFrontDeskRequest {
        
        public FrontDeskRequestClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public FrontDeskRequestClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public FrontDeskRequestClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public FrontDeskRequestClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public FrontDeskRequestClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void ListenToServer() {
            base.Channel.ListenToServer();
        }
    }
}
