//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSMS.Presentation.Impl.DinningService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DinningService.IDinningService")]
    public interface IDinningService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDinningItemService/QueryItemList", ReplyAction="http://tempuri.org/IDinningItemService/QueryItemListResponse")]
        System.Collections.Generic.List<HCSMS.Model.SaleItem> QueryItemList(HCSMS.Model.QueryCriteria queryConditon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDinningItemService/QueryItem", ReplyAction="http://tempuri.org/IDinningItemService/QueryItemResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HCSMS.Model.SaleItem))]
        HCSMS.Model.Item QueryItem(string itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDinningItemService/GetSpecialOfferForItem", ReplyAction="http://tempuri.org/IDinningItemService/GetSpecialOfferForItemResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HCSMS.Model.SaleItem))]
        System.Collections.Generic.List<HCSMS.Model.SpecialOffer> GetSpecialOfferForItem(HCSMS.Model.Item anItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDinningItemService/GetRecommendItem", ReplyAction="http://tempuri.org/IDinningItemService/GetRecommendItemResponse")]
        System.Collections.Generic.List<HCSMS.Model.SaleItem> GetRecommendItem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDinningItemService/OrderItem", ReplyAction="http://tempuri.org/IDinningItemService/OrderItemResponse")]
        void OrderItem(string tableNumber, System.Collections.Generic.List<HCSMS.Model.Item> itemList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDinningItemService/DeorderItem", ReplyAction="http://tempuri.org/IDinningItemService/DeorderItemResponse")]
        void DeorderItem(string tableNumber, System.Collections.Generic.List<HCSMS.Model.Item> itemList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDinningItemService/ChangeItem", ReplyAction="http://tempuri.org/IDinningItemService/ChangeItemResponse")]
        void ChangeItem(string tableNumber, System.Collections.Generic.Dictionary<HCSMS.Model.Item, HCSMS.Model.Item> itemPair);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDinningItemService/SetSpecialOfferForItem", ReplyAction="http://tempuri.org/IDinningItemService/SetSpecialOfferForItemResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HCSMS.Model.SaleItem))]
        void SetSpecialOfferForItem(HCSMS.Model.Item anItem, System.Collections.Generic.List<HCSMS.Model.SpecialOffer> offerList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDinningItemService/SetItem", ReplyAction="http://tempuri.org/IDinningItemService/SetItemResponse")]
        void SetItem(System.Collections.Generic.List<HCSMS.Model.SaleItem> itemList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDinningItemService/UpdateItem", ReplyAction="http://tempuri.org/IDinningItemService/UpdateItemResponse")]
        void UpdateItem(System.Collections.Generic.List<HCSMS.Model.Item> itemList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDinningTableService/QueryTable", ReplyAction="http://tempuri.org/IDinningTableService/QueryTableResponse")]
        HCSMS.Model.Table QueryTable(string tableNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDinningTableService/QueryTableList", ReplyAction="http://tempuri.org/IDinningTableService/QueryTableListResponse")]
        System.Collections.Generic.List<HCSMS.Model.Table> QueryTableList(HCSMS.Model.QueryCriteria condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDinningTableService/QueryAvailableTable", ReplyAction="http://tempuri.org/IDinningTableService/QueryAvailableTableResponse")]
        System.Collections.Generic.List<HCSMS.Model.Table> QueryAvailableTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDinningTableService/GetTable", ReplyAction="http://tempuri.org/IDinningTableService/GetTableResponse")]
        System.Collections.Generic.List<HCSMS.Model.Table> GetTable(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDinningTableService/UseTable", ReplyAction="http://tempuri.org/IDinningTableService/UseTableResponse")]
        void UseTable(System.Collections.Generic.Dictionary<HCSMS.Model.Table, HCSMS.Model.DinningTable> tables);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDinningTableService/ChangeTable", ReplyAction="http://tempuri.org/IDinningTableService/ChangeTableResponse")]
        void ChangeTable(string oldTableNumber, string newTableNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDinningService/AcceptServerReply", ReplyAction="http://tempuri.org/IDinningService/AcceptServerReplyResponse")]
        void AcceptServerReply(string callBackId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDinningServiceChannel : HCSMS.Presentation.Impl.DinningService.IDinningService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DinningServiceClient : System.ServiceModel.ClientBase<HCSMS.Presentation.Impl.DinningService.IDinningService>, HCSMS.Presentation.Impl.DinningService.IDinningService {
        
        public DinningServiceClient() {
        }
        
        public DinningServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DinningServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DinningServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DinningServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<HCSMS.Model.SaleItem> QueryItemList(HCSMS.Model.QueryCriteria queryConditon) {
            return base.Channel.QueryItemList(queryConditon);
        }
        
        public HCSMS.Model.Item QueryItem(string itemId) {
            return base.Channel.QueryItem(itemId);
        }
        
        public System.Collections.Generic.List<HCSMS.Model.SpecialOffer> GetSpecialOfferForItem(HCSMS.Model.Item anItem) {
            return base.Channel.GetSpecialOfferForItem(anItem);
        }
        
        public System.Collections.Generic.List<HCSMS.Model.SaleItem> GetRecommendItem() {
            return base.Channel.GetRecommendItem();
        }
        
        public void OrderItem(string tableNumber, System.Collections.Generic.List<HCSMS.Model.Item> itemList) {
            base.Channel.OrderItem(tableNumber, itemList);
        }
        
        public void DeorderItem(string tableNumber, System.Collections.Generic.List<HCSMS.Model.Item> itemList) {
            base.Channel.DeorderItem(tableNumber, itemList);
        }
        
        public void ChangeItem(string tableNumber, System.Collections.Generic.Dictionary<HCSMS.Model.Item, HCSMS.Model.Item> itemPair) {
            base.Channel.ChangeItem(tableNumber, itemPair);
        }
        
        public void SetSpecialOfferForItem(HCSMS.Model.Item anItem, System.Collections.Generic.List<HCSMS.Model.SpecialOffer> offerList) {
            base.Channel.SetSpecialOfferForItem(anItem, offerList);
        }
        
        public void SetItem(System.Collections.Generic.List<HCSMS.Model.SaleItem> itemList) {
            base.Channel.SetItem(itemList);
        }
        
        public void UpdateItem(System.Collections.Generic.List<HCSMS.Model.Item> itemList) {
            base.Channel.UpdateItem(itemList);
        }
        
        public HCSMS.Model.Table QueryTable(string tableNumber) {
            return base.Channel.QueryTable(tableNumber);
        }
        
        public System.Collections.Generic.List<HCSMS.Model.Table> QueryTableList(HCSMS.Model.QueryCriteria condition) {
            return base.Channel.QueryTableList(condition);
        }
        
        public System.Collections.Generic.List<HCSMS.Model.Table> QueryAvailableTable() {
            return base.Channel.QueryAvailableTable();
        }
        
        public System.Collections.Generic.List<HCSMS.Model.Table> GetTable(System.DateTime date) {
            return base.Channel.GetTable(date);
        }
        
        public void UseTable(System.Collections.Generic.Dictionary<HCSMS.Model.Table, HCSMS.Model.DinningTable> tables) {
            base.Channel.UseTable(tables);
        }
        
        public void ChangeTable(string oldTableNumber, string newTableNumber) {
            base.Channel.ChangeTable(oldTableNumber, newTableNumber);
        }
        
        public void AcceptServerReply(string callBackId) {
            base.Channel.AcceptServerReply(callBackId);
        }
    }
}
