//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSMS.Presentation.Impl.ReservationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReservationService.IReservationService")]
    public interface IReservationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/MakeReservation", ReplyAction="http://tempuri.org/IReservationService/MakeReservationResponse")]
        void MakeReservation(HCSMS.Model.PreorderTable table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/CancelReservation", ReplyAction="http://tempuri.org/IReservationService/CancelReservationResponse")]
        void CancelReservation(HCSMS.Model.PreorderTable table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/GetReservationList", ReplyAction="http://tempuri.org/IReservationService/GetReservationListResponse")]
        System.Collections.Generic.List<HCSMS.Model.PreorderTable> GetReservationList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/ChangeReservation", ReplyAction="http://tempuri.org/IReservationService/ChangeReservationResponse")]
        void ChangeReservation(HCSMS.Model.PreorderTable table);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReservationServiceChannel : HCSMS.Presentation.Impl.ReservationService.IReservationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservationServiceClient : System.ServiceModel.ClientBase<HCSMS.Presentation.Impl.ReservationService.IReservationService>, HCSMS.Presentation.Impl.ReservationService.IReservationService {
        
        public ReservationServiceClient() {
        }
        
        public ReservationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void MakeReservation(HCSMS.Model.PreorderTable table) {
            base.Channel.MakeReservation(table);
        }
        
        public void CancelReservation(HCSMS.Model.PreorderTable table) {
            base.Channel.CancelReservation(table);
        }
        
        public System.Collections.Generic.List<HCSMS.Model.PreorderTable> GetReservationList() {
            return base.Channel.GetReservationList();
        }
        
        public void ChangeReservation(HCSMS.Model.PreorderTable table) {
            base.Channel.ChangeReservation(table);
        }
    }
}
